#include "./Processors/DenoiseStrategies/DefaultDenoiseStrategy.h"
#include "./DenoiseStrategies/LateralInhibition.h"
#include "./DenoiseStrategies/Pmdiff2.h"
#include "./DenoiseStrategies/BaseWeightBGP.h"
#include "./DenoiseStrategies/DoublehistEqual.h"
#include "./DenoiseStrategies/FD.h"
#include "./DenoiseStrategies/LMPM.h"
#include "./DenoiseStrategies/LocalMeanContrast.h"
#include "./DenoiseStrategies/Localshannon.h"
#include "./DenoiseStrategies/Localstd.h"
#include "./DenoiseStrategies/MaxMedianFilter.h"
#include "./DenoiseStrategies/Pmdiff1.h"
#include "./DenoiseStrategies/Pmdiffmy.h"
#include "./DenoiseStrategies/TDLMS.h"

#include "./Processors/SegmentStrategies/DefaultSegmentStrategy.h"